/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Booktype;

/**
 *
 * @author Gihan
 */
public class BooktypeUI extends javax.swing.JFrame {
    Booktype booktype;
    int selectid;
    
    
    /**
     * Creates new form BooktypeUI
     */
    public BooktypeUI() {
        initComponents();
        booktype = new Booktype();
        loadTable(booktype.getAllBookTypeDetails()); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tbtype = new javax.swing.JTextField();
        badd = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbtypes = new javax.swing.JTable();
        bdeactivate = new javax.swing.JButton();
        bactivate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Type Window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Book Type:");

        tbtype.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbtype.setForeground(new java.awt.Color(51, 102, 255));

        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        tblbtypes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblbtypes.setForeground(new java.awt.Color(0, 102, 255));
        tblbtypes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Type", "Activate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbtypes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblbtypes.setRowHeight(22);
        tblbtypes.setSelectionBackground(new java.awt.Color(0, 0, 255));
        tblbtypes.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tblbtypes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbtypesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbtypes);
        tblbtypes.getColumnModel().getColumn(0).setMinWidth(50);
        tblbtypes.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblbtypes.getColumnModel().getColumn(0).setMaxWidth(50);
        tblbtypes.getColumnModel().getColumn(2).setMinWidth(60);
        tblbtypes.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblbtypes.getColumnModel().getColumn(2).setMaxWidth(60);

        bdeactivate.setText("Deactivate");
        bdeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeactivateActionPerformed(evt);
            }
        });

        bactivate.setText("Activate");
        bactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bactivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bdeactivate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bactivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tbtype))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tbtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-397)/2, (screenSize.height-464)/2, 397, 464);
    }// </editor-fold>//GEN-END:initComponents

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        if(!tbtype.getText().trim().equals("")){
            booktype = new Booktype();
            booktype.setBooktype(tbtype.getText()); 
                if(booktype.addNewBookType()){
                    JOptionPane.showMessageDialog(null, "Done! Added New Book Type", "Done!", 1);
                    loadTable(booktype.getAllBookTypeDetails());
                    tbtype.setText(""); 
                }else{
                    JOptionPane.showMessageDialog(null, "Error! While adding book type!", "Error!", 0);
                }
        }else{
            JOptionPane.showMessageDialog(null, "Type the Book Type!", "Warning!", 2);
        }
    }//GEN-LAST:event_baddActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        if(tblbtypes.getSelectedRow() != -1){
            if(!tbtype.getText().trim().equals("")){
                booktype = new Booktype();
                booktype.setBooktype(tbtype.getText()); 
                    if(booktype.updateBookType(selectid, tbtype.getText())){
                        JOptionPane.showMessageDialog(null, "Done! Updated the Selected Book Type", "Done!", 1);
                        loadTable(booktype.getAllBookTypeDetails());
                        tbtype.setText(""); 
                    }else{
                        JOptionPane.showMessageDialog(null, "Error! While updating book type!", "Error!", 0);
                    }
            }else{
                JOptionPane.showMessageDialog(null, "Type the New Book Type!", "Warning!", 2);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select the Type from Table", "Warning!", 2);
        }
        
        
    }//GEN-LAST:event_bupdateActionPerformed

    private void tblbtypesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbtypesMouseClicked
        selectid = Integer.parseInt(tblbtypes.getValueAt(tblbtypes.getSelectedRow(), 0).toString()); 
        tbtype.setText(""+tblbtypes.getValueAt(tblbtypes.getSelectedRow(), 1));
        
    }//GEN-LAST:event_tblbtypesMouseClicked

    private void bdeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeactivateActionPerformed
        if(tblbtypes.getSelectedRow() != -1){
            if(JOptionPane.showConfirmDialog(null, "Do You Really Want to Deactivate the Selected Book Type?", "Question", 0) == 0){
                    booktype = new Booktype();
                        if(booktype.deativateBookType(Integer.parseInt(tblbtypes.getValueAt(tblbtypes.getSelectedRow(), 0).toString()))){ 
                            JOptionPane.showMessageDialog(null, "Done! Deactivated the Book Type!", "Done!", 2);
                            loadTable(booktype.getAllBookTypeDetails());
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "Error! While Deactivating, Try Again!", "Error!", 1);
                        }
                }
        }else{
            JOptionPane.showMessageDialog(null, "Select the Type from Table", "Warning!", 2);
        }
    }//GEN-LAST:event_bdeactivateActionPerformed

    private void bactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bactivateActionPerformed
        if(tblbtypes.getSelectedRow() != -1){
            if(JOptionPane.showConfirmDialog(null, "Do You Really Want to Deactivate the Selected Book Type?", "Question", 0) == 0){
                    booktype = new Booktype();
                        if(booktype.activateBookType(Integer.parseInt(tblbtypes.getValueAt(tblbtypes.getSelectedRow(), 0).toString()))){ 
                            JOptionPane.showMessageDialog(null, "Done! Deactivated the Book Type!", "Done!", 2);
                            loadTable(booktype.getAllBookTypeDetails());
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "Error! While Deactivating, Try Again!", "Error!", 1);
                        }
                }
        }else{
            JOptionPane.showMessageDialog(null, "Select the Type from Table", "Warning!", 2);
        }
    }//GEN-LAST:event_bactivateActionPerformed
    
    void loadTable(ResultSet rs){
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblbtypes.getModel();
        
        try {
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getInt("btypeid"));
                vec.add(rs.getString("type"));
                vec.add(rs.getInt("isactive"));
                dt.addRow(vec); 
            }
            
        } catch (SQLException ex) {
            System.out.println("Error from table interface: " + ex);;
        }
        
    }
    
    void clearTable(){
        DefaultTableModel dt = (DefaultTableModel) tblbtypes.getModel();
        int rows = tblbtypes.getRowCount();
            for(int x=0; x < rows; x++){
                dt.removeRow(0); 
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooktypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooktypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooktypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooktypeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BooktypeUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bactivate;
    private javax.swing.JButton badd;
    private javax.swing.JButton bdeactivate;
    private javax.swing.JButton bupdate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbtypes;
    private javax.swing.JTextField tbtype;
    // End of variables declaration//GEN-END:variables
}
