/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Dealer;
import model.Dealerbalance;

/**
 *
 * @author Gihan
 */
public class DelaerUI extends javax.swing.JFrame {
    Dealer dealer;
    Dealerbalance dealerbalance;
    
    String dname;
    String daddress;
    String dcontact;
    double doutstanding;
    int srow;
    
    /**
     * Creates new form DelaerUI
     */
    public DelaerUI() {
        initComponents();
        
        dealer = new Dealer();
        loadTable(dealer.getDealerToTable()); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        taddress = new javax.swing.JTextField();
        badd = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldealers = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tcontact = new javax.swing.JTextField();
        bdeactivate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbsearch = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tsearch = new javax.swing.JTextField();
        chsearch = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        toutstanding = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dealer Window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Dealer Name:");

        tname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tname.setForeground(new java.awt.Color(51, 102, 255));
        tname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnameKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Address:");

        taddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        taddress.setForeground(new java.awt.Color(51, 102, 255));
        taddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                taddressKeyPressed(evt);
            }
        });

        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        tbldealers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbldealers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Contact", "Outstanding"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldealers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbldealers.setRowHeight(22);
        tbldealers.setSelectionBackground(new java.awt.Color(0, 0, 255));
        tbldealers.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tbldealers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldealersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldealers);
        tbldealers.getColumnModel().getColumn(0).setMinWidth(50);
        tbldealers.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbldealers.getColumnModel().getColumn(0).setMaxWidth(50);
        tbldealers.getColumnModel().getColumn(1).setMinWidth(250);
        tbldealers.getColumnModel().getColumn(1).setPreferredWidth(250);
        tbldealers.getColumnModel().getColumn(1).setMaxWidth(250);
        tbldealers.getColumnModel().getColumn(3).setMinWidth(100);
        tbldealers.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbldealers.getColumnModel().getColumn(3).setMaxWidth(100);
        tbldealers.getColumnModel().getColumn(4).setMinWidth(100);
        tbldealers.getColumnModel().getColumn(4).setPreferredWidth(100);
        tbldealers.getColumnModel().getColumn(4).setMaxWidth(100);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Contact No:");

        tcontact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tcontact.setForeground(new java.awt.Color(51, 102, 255));
        tcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcontactKeyPressed(evt);
            }
        });

        bdeactivate.setText("Deactivate");
        bdeactivate.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Search By:");

        cmbsearch.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbsearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "City" }));

        jLabel2.setText("Search Term:");

        tsearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tsearch.setForeground(new java.awt.Color(255, 51, 51));

        chsearch.setBackground(new java.awt.Color(255, 255, 255));
        chsearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chsearch.setText("Search");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(chsearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chsearch)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("O.Standing:");

        toutstanding.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        toutstanding.setForeground(new java.awt.Color(51, 102, 255));
        toutstanding.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                toutstandingKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bdeactivate))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taddress, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(toutstanding, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(taddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(toutstanding, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-878)/2, (screenSize.height-580)/2, 878, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        if(!tname.getText().trim().equals("") && !taddress.getText().trim().equals("") && !tcontact.getText().trim().equals("")){
            dealer = new Dealer();
            dealer.setDtypeid(1);
            dealer.setName(tname.getText());  
            dealer.setAddress(taddress.getText()); 
            dealer.setContact(tcontact.getText()); 
            dealer.setIsactive(1); 
                if(JOptionPane.showConfirmDialog(null, "Sure to Add this Dealer?", "Question", 0) == 0){
                    
                    if(dealer.addNewDealer()){
                        dealerbalance = new Dealerbalance();
                        dealerbalance.setDealerid(dealer.getLatDealerId()); 
                        dealerbalance.setNetbalance(0.00);  
                        dealerbalance.setBalancedate(getToday());
                        
                            if(dealerbalance.setInitialDealerBalance()){
                                JOptionPane.showMessageDialog(null, "Done! Successfully Added New Dealer!", "Done!", 1);
                                clearAll();
                                loadTable(dealer.getDealerToTable());
                                tname.grabFocus();
                            }else{
                                JOptionPane.showMessageDialog(null, "Error! While Setting Default Dealer Balance, Try Again!", "Warning!", 2);
                            }
                            
                    }else{
                        JOptionPane.showMessageDialog(null, "Error! While Adding Dealer, Try Again!", "Warning!", 2);
                    }
                }
                
        }else{
            JOptionPane.showMessageDialog(null, "Fill all Details!", "Warning!", 2);
        }
    }//GEN-LAST:event_baddActionPerformed

    private void tnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            taddress.grabFocus();
        }
    }//GEN-LAST:event_tnameKeyPressed

    private void taddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taddressKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tcontact.grabFocus();
        }
    }//GEN-LAST:event_taddressKeyPressed

    private void tcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcontactKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            baddActionPerformed(null); 
        }
    }//GEN-LAST:event_tcontactKeyPressed

    private void toutstandingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toutstandingKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_toutstandingKeyPressed

    private void tbldealersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldealersMouseClicked
//        double val = 3.11111;
//        DecimalFormat df = new DecimalFormat("#.##");
//        System.out.println("Val: " + df.format(val));
        
        srow = tbldealers.getSelectedRow();
        badd.setEnabled(false); 
        
        if(srow != -1){
            dname = tbldealers.getValueAt(srow, 1).toString();
            daddress = tbldealers.getValueAt(srow, 2).toString();
            dcontact = tbldealers.getValueAt(srow, 3).toString();
            doutstanding = Double.parseDouble(tbldealers.getValueAt(srow, 4).toString()); 
            
        }
        tname.setText(dname); 
        taddress.setText(daddress);
        tcontact.setText(dcontact);
        toutstanding.setText(""+doutstanding);
        
    }//GEN-LAST:event_tbldealersMouseClicked

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        if(!tname.getText().trim().equals("") && !taddress.getText().trim().equals("") && !tcontact.getText().trim().equals("") && !toutstanding.getText().trim().equals("")){
            dealer = new Dealer();
            dealer.setName(tname.getText());  
            dealer.setAddress(taddress.getText()); 
            dealer.setContact(tcontact.getText()); 
                if(dealer.updateDealer(Integer.parseInt(tbldealers.getValueAt(srow, 0).toString()), Double.parseDouble(toutstanding.getText()))){
                    JOptionPane.showMessageDialog(null, "Done! Updated Successfully!", "Done!", 2);
                    clearAll();
                    loadTable(dealer.getDealerToTable());
                    tname.grabFocus();  
                }else{
                    JOptionPane.showMessageDialog(null, "Error! While Updating", "Error!", 0);
                }
        }else{
            JOptionPane.showMessageDialog(null, "Fill all Details to Update!", "Warning!", 2);   
        }
        
        
        
    }//GEN-LAST:event_bupdateActionPerformed
    
    void clearAll(){
        tname.setText(""); 
        taddress.setText("");
        tcontact.setText("");
        
    }
    
    void loadTable(ResultSet rs){
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tbldealers.getModel();
        
        try {
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getInt("dealerid"));
                vec.add(rs.getString("name"));
                vec.add(rs.getString("address"));
                vec.add(rs.getString("contact")); 
                vec.add(rs.getDouble("netbalance"));
                dt.addRow(vec); 
            }
            
        } catch (SQLException ex) {
            System.out.println("Error from table interface: " + ex);;
        }
        
    }
    
    void clearTable(){
        DefaultTableModel dt = (DefaultTableModel) tbldealers.getModel();
        int rows = tbldealers.getRowCount();
            for(int x=0; x < rows; x++){
                dt.removeRow(0); 
            }
        
    }
    
    String getToday(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String today = df.format(cal.getTime());
        
        return today;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelaerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelaerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelaerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelaerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DelaerUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton bdeactivate;
    private javax.swing.JButton bupdate;
    private javax.swing.JCheckBox chsearch;
    private javax.swing.JComboBox cmbsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField taddress;
    private javax.swing.JTable tbldealers;
    private javax.swing.JTextField tcontact;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField toutstanding;
    private javax.swing.JTextField tsearch;
    // End of variables declaration//GEN-END:variables
}
