/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import model.User;

/**
 *
 * @author Gihan
 */
public class MainUI extends javax.swing.JFrame {
    public static String loguser;
    public int usertype;
    public static int userid;
    MainUI mainwindow;
    User user;
    private BooktypeUI booktype = null;
    
    
    /**
     * Creates new form MainUI
     */
    
    public void setLogUser(String username, MainUI window){
        this.mainwindow = window;
        mainwindow.loguser = username;
//        window.setTitle("Wel Come! Medical Center Management System: " + MainUI.loguser + " (" + getUtypeId() + ") "); 
//        window.repaint();
         
        user = new User();
        try {
            this.usertype = user.getUserTypeId(loguser);
            this.userid = user.getUserId(loguser);
            System.out.println("Type1: " + usertype);
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
        window.setTitle("Wel Come to Mydealer: " + MainUI.loguser + " (" + getUtypeId() + ") " + " - UserId: " + MainUI.userid); 
        window.repaint();
        window.setVisible(true);
        
        if(usertype == 2){
            bbookprice.setEnabled(false);
            bdiscounts.setEnabled(false);
            busermanage.setEnabled(false);
        }
        
    }
    
    public MainUI() {
        initComponents();
        
        Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, screensize.width, screensize.height);
        
        tabmain.removeAll();
        InvoiceUI invoiceui = new InvoiceUI();
        tabmain.add("Invoice UI", invoiceui);
    }
    
    public int getUtypeId(){
        int thisid = usertype;
        return thisid;
    }
    
    public String getCurrentUser(){
        String thisuser = loguser;
        return thisuser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        binvoice = new javax.swing.JButton();
        tabmain = new javax.swing.JTabbedPane();
        binvoice1 = new javax.swing.JButton();
        binvoice2 = new javax.swing.JButton();
        bbooktype = new javax.swing.JButton();
        bdiscounts = new javax.swing.JButton();
        bbookprice = new javax.swing.JButton();
        bbookstock = new javax.swing.JButton();
        busermanage = new javax.swing.JButton();
        cmbreports = new javax.swing.JComboBox();
        busermanage1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point of Sales System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        binvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pos_invoice.png"))); // NOI18N
        binvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binvoiceActionPerformed(evt);
            }
        });

        binvoice1.setText("Books");
        binvoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binvoice1ActionPerformed(evt);
            }
        });

        binvoice2.setText("Delalers");
        binvoice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binvoice2ActionPerformed(evt);
            }
        });

        bbooktype.setText("Book Types");
        bbooktype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbooktypeActionPerformed(evt);
            }
        });

        bdiscounts.setText("Discounts");
        bdiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdiscountsActionPerformed(evt);
            }
        });

        bbookprice.setText("Book Price");
        bbookprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbookpriceActionPerformed(evt);
            }
        });

        bbookstock.setText("Stocks");
        bbookstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbookstockActionPerformed(evt);
            }
        });

        busermanage.setText("User Manage");
        busermanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busermanageActionPerformed(evt);
            }
        });

        cmbreports.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date-Summary", "Date-Detailed", "Book-Single", "Book-All", "Agent-Books", "Agent-All" }));

        busermanage1.setText("Report Window");
        busermanage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busermanage1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(binvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(binvoice2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(binvoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bbookprice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bbooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bbookstock, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bdiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busermanage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbreports, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(busermanage1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addComponent(tabmain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(binvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(binvoice1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(binvoice2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bbooktype, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bdiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bbookprice, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bbookstock, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(busermanage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(busermanage1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbreports))
                .addGap(18, 18, 18)
                .addComponent(tabmain, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void binvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binvoiceActionPerformed
        tabmain.removeAll();
        InvoiceUI invoiceui = new InvoiceUI();
        tabmain.add("Invoice UI", invoiceui);
    }//GEN-LAST:event_binvoiceActionPerformed

    private void binvoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binvoice1ActionPerformed
        new ProductsUI().setVisible(true); 
    }//GEN-LAST:event_binvoice1ActionPerformed

    private void binvoice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binvoice2ActionPerformed
        new DelaerUI().setVisible(true); 
    }//GEN-LAST:event_binvoice2ActionPerformed

    private void bbooktypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbooktypeActionPerformed
      booktype = (booktype == null) ? new BooktypeUI() : booktype;
      booktype.setVisible(true);
        
    }//GEN-LAST:event_bbooktypeActionPerformed

    private void bdiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdiscountsActionPerformed
        new DiscountUI().setVisible(true); 
    }//GEN-LAST:event_bdiscountsActionPerformed

    private void bbookpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbookpriceActionPerformed
        tabmain.removeAll();
        BookpriceUI bookpriceui = new BookpriceUI();
        tabmain.add("Book Price", bookpriceui);
    }//GEN-LAST:event_bbookpriceActionPerformed

    private void bbookstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbookstockActionPerformed
        tabmain.removeAll();
        StockUI stockui = new StockUI();
        tabmain.add("Stock Manage", stockui);
    }//GEN-LAST:event_bbookstockActionPerformed

    private void busermanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busermanageActionPerformed
        new UsermanageUI().setVisible(true); 
    }//GEN-LAST:event_busermanageActionPerformed

    private void busermanage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busermanage1ActionPerformed
        if(cmbreports.getSelectedItem().equals("Date-Summary")){
            new Reportdatesum().setVisible(true); 
        }else if(cmbreports.getSelectedItem().equals("Date-Detailed")){
            new Reportsdatedetail().setVisible(true);
        }else if(cmbreports.getSelectedItem().equals("Book-Single")){
            new Reportbooksingle().setVisible(true); 
        }else if(cmbreports.getSelectedItem().equals("Book-All")){
            new Reportbookall().setVisible(true); 
        }else if(cmbreports.getSelectedItem().equals("Agent-Books")){
            new Reportagentbooks().setVisible(true); 
        }else if(cmbreports.getSelectedItem().equals("Agent-All")){
            new Reportagentall().setVisible(true); 
        }
        
    }//GEN-LAST:event_busermanage1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbookprice;
    private javax.swing.JButton bbookstock;
    private javax.swing.JButton bbooktype;
    private javax.swing.JButton bdiscounts;
    private javax.swing.JButton binvoice;
    private javax.swing.JButton binvoice1;
    private javax.swing.JButton binvoice2;
    private javax.swing.JButton busermanage;
    private javax.swing.JButton busermanage1;
    private javax.swing.JComboBox cmbreports;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane tabmain;
    // End of variables declaration//GEN-END:variables
}
