/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Repbooksummary;

/**
 *
 * @author Gihan
 */
public class Reportbookall extends javax.swing.JFrame implements Printable{
    Repbooksummary repsummary;
    Book book;
    
    /**
     * Creates new form Reportbookall
     */
    public Reportbookall() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtfrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dtto = new com.toedter.calendar.JDateChooser();
        bgenerate = new javax.swing.JButton();
        bexport = new javax.swing.JButton();
        bprint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbooks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Total Report");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("From:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("To:");

        bgenerate.setText("Generate Report");
        bgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgenerateActionPerformed(evt);
            }
        });

        bexport.setText("Export to CSV");
        bexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexportActionPerformed(evt);
            }
        });

        bprint.setText("Print Report");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bexport, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bgenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(bexport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tblbooks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tblbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B.ID", "Book Title", "Sold Qty", "Sold Amount", "Return Qty", "Return Amount", "Sold/Return %"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblbooks.setRowHeight(22);
        tblbooks.setSelectionBackground(new java.awt.Color(51, 51, 255));
        tblbooks.setSelectionForeground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(tblbooks);
        tblbooks.getColumnModel().getColumn(0).setMinWidth(50);
        tblbooks.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblbooks.getColumnModel().getColumn(0).setMaxWidth(50);
        tblbooks.getColumnModel().getColumn(2).setMinWidth(80);
        tblbooks.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblbooks.getColumnModel().getColumn(2).setMaxWidth(80);
        tblbooks.getColumnModel().getColumn(3).setMinWidth(100);
        tblbooks.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblbooks.getColumnModel().getColumn(3).setMaxWidth(100);
        tblbooks.getColumnModel().getColumn(4).setMinWidth(80);
        tblbooks.getColumnModel().getColumn(4).setPreferredWidth(80);
        tblbooks.getColumnModel().getColumn(4).setMaxWidth(80);
        tblbooks.getColumnModel().getColumn(5).setMinWidth(100);
        tblbooks.getColumnModel().getColumn(5).setPreferredWidth(100);
        tblbooks.getColumnModel().getColumn(5).setMaxWidth(100);
        tblbooks.getColumnModel().getColumn(6).setMinWidth(100);
        tblbooks.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblbooks.getColumnModel().getColumn(6).setMaxWidth(100);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-938)/2, (screenSize.height-689)/2, 938, 689);
    }// </editor-fold>//GEN-END:initComponents

    private void bgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgenerateActionPerformed
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblbooks.getModel();
        double percentage = 0;
        
        try {
            book = new Book(); 
            repsummary = new Repbooksummary();
            
            ResultSet rs = book.getBooksDetails();
            
                while(rs.next()){
                    Vector vec = new Vector();
                    int bookid = rs.getInt("bookid");
                    String booktitle = rs.getString("title");
                    int soldqty = repsummary.getTotalSoldQty(getFromDate(), getToDate(), bookid);
                    double soldamount = repsummary.getTotalSoldAmount(getFromDate(), getToDate(), bookid);
                    int returnqty = repsummary.getTotalReturnQty(getFromDate(), getToDate(), bookid);
                    double returnamount = repsummary.getTotalReturnAmount(getFromDate(), getToDate(), bookid);
                    
                    if(soldqty != 0){
                        percentage = ((double)returnqty / (double)soldqty) * 100;
                    }else{
                        percentage = 0.0;
                    }
                
                    DecimalFormat decimal = new DecimalFormat("#.##");
                    
                    vec.add(bookid);
                    vec.add(booktitle);
                    vec.add(soldqty);
                    vec.add(soldamount);
                    vec.add(returnqty);
                    vec.add(returnamount);
                    vec.add(Double.valueOf(decimal.format(percentage))); 
                    dt.addRow(vec); 
                    
                }
                
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bgenerateActionPerformed

    private void bexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexportActionPerformed
        
        
    }//GEN-LAST:event_bexportActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        if(tblbooks.getRowCount() > 0){
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setPrintable(this); 
        
            if(pj.printDialog()){
                try {
                    System.out.println("Starting........");
                    pj.print();
                    System.out.println("Done!......");
                } catch (Exception e) {
                    System.out.println("Error: Print Error: " + e);
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "First Get Data to the Table!", "Warning!", 2); 
        }
        
        
        
    }//GEN-LAST:event_bprintActionPerformed
    
    void loadTable(ResultSet rs1, ResultSet rs2){
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblbooks.getModel();
        
        try {
            while(rs1.next() && rs2.next()){
                Vector vec = new Vector();
                vec.add(rs1.getInt("bookid"));
                vec.add(null); 
                vec.add(rs1.getInt("soldqty"));
                vec.add(rs1.getInt("soldamount")); 
                vec.add(rs2.getInt("returnqty"));
                vec.add(rs2.getInt("returnamount"));
                dt.addRow(vec); 
            }
            
//            while(rs2.next()){
//                Vector vec = new Vector();
//                vec.add(rs2.getInt("returnqty"));
//                vec.add(rs2.getInt("returnamount")); 
//                dt.addRow(vec); 
//            }
            
        } catch (SQLException ex) {
            System.out.println("Error from table interface: " + ex);;
        }
        
    }
    
    void clearTable(){
        DefaultTableModel dt = (DefaultTableModel) tblbooks.getModel();
        int rows = tblbooks.getRowCount();
            for(int x=0; x < rows; x++){
                dt.removeRow(0); 
            }
        
    }
    
    String getFromDate(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String fromdate = df.format(dtfrom.getDate());
        
        return fromdate;
    }
    
    String getToDate(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String todate = df.format(dtto.getDate());
        
        return todate;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportbookall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportbookall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportbookall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportbookall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reportbookall().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexport;
    private javax.swing.JButton bgenerate;
    private javax.swing.JButton bprint;
    private com.toedter.calendar.JDateChooser dtfrom;
    private com.toedter.calendar.JDateChooser dtto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbooks;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics g, PageFormat pf, int pageIndex) throws PrinterException {
        if(pageIndex > 0){
            return NO_SUCH_PAGE;
        }
        
        int rows = tblbooks.getRowCount();
        int h = 120;
        
        Graphics2D gr2d = (Graphics2D)g;
        gr2d.translate(pf.getImageableX(), pf.getImageableY());
        
        Font fonth = new Font("arial", Font.BOLD, 12);
        Font fontn = new Font("arial", Font.PLAIN, 10);
        Font fontd = new Font("arial", Font.PLAIN, 8);
        
        g.setFont(fonth); 
        g.drawString("Sathara Prakashakayo", 100, 30); 
        g.setFont(fontn); 
        g.drawString("Books Sales Report", 110, 50);
        
        g.drawLine(20, 60, 300, 60);
        
        g.drawString("From: ", 50, 70);
        g.drawString("" + getFromDate(), 180, 70);
        g.drawString("To: ", 50, 90);
        g.drawString("" + getToDate(), 180, 90);
        g.setFont(fontd); 
        
        g.drawLine(20, 100, 300, 100);
        g.drawString("B.ID", 20, 110);
        g.drawString("Book Title", 50, 110);
        g.drawString("Sold", 150, 110);
        g.drawString("Qty", 150, 120);
        g.drawString("Sold", 180, 110);
        g.drawString("Amount", 180, 120);
        g.drawString("Return", 210, 110);
        g.drawString("Qty", 210, 120);
        g.drawString("Return", 240, 110);
        g.drawString("Amount", 240, 120);
        g.drawString("Percentage", 270, 110);
        g.drawLine(20, 120, 300, 120);
        
        for(int x = 0; x < rows; x++){
            h += 15;
            String bid = tblbooks.getValueAt(x, 0).toString();
            String btitle = tblbooks.getValueAt(x, 1).toString();
            String sqty = tblbooks.getValueAt(x, 2).toString();
            String samount = tblbooks.getValueAt(x, 3).toString();
            String rqty = tblbooks.getValueAt(x, 4).toString();
            String ramount = tblbooks.getValueAt(x, 5).toString();
            String per = tblbooks.getValueAt(x, 6).toString();
            
            g.drawString(bid, 20, h);
            g.drawString(btitle, 50, h);
            g.drawString(sqty, 150, h);
            g.drawString(samount, 180, h);
            g.drawString(rqty, 210, h);
            g.drawString(ramount, 240, h);
            g.drawString(per, 270, h);
            
            
        }
        
        
        return PAGE_EXISTS;
        
    }
}
