/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import control.Multiuse;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import model.Repbooksummary;

/**
 *
 * @author Gihan
 */
public class Reportbooksingle extends javax.swing.JFrame implements Printable{
    Multiuse multiuse;
    Repbooksummary repbooksum;
    
    int bookid;
    int soldqty;
    int returnqty;
    String booktitle;
    double soldamount;
    double returnamount;
    double percentage;
    
    
    /**
     * Creates new form Reportbooksingle
     */
    public Reportbooksingle() {
        initComponents();
        
        listbook.setVisible(false);  
        scrollbook.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtfrom = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dtto = new com.toedter.calendar.JDateChooser();
        bgenerate = new javax.swing.JButton();
        tbook = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        scrollbook = new javax.swing.JScrollPane();
        listbook = new javax.swing.JList();
        bprint = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ltotsold = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ltotsoldamount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ltotreturn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ltotretamount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lpercentage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Single Report");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("From:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, 34));
        jPanel2.add(dtfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 12, 141, 34));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("To:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 12, -1, 34));
        jPanel2.add(dtto, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 12, 141, 34));

        bgenerate.setText("Generate Report");
        bgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgenerateActionPerformed(evt);
            }
        });
        jPanel2.add(bgenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 65, 130, 37));

        tbook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbook.setForeground(new java.awt.Color(255, 51, 51));
        tbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbookKeyReleased(evt);
            }
        });
        jPanel2.add(tbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 280, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Book:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 76, -1, -1));

        listbook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        listbook.setForeground(new java.awt.Color(255, 51, 51));
        listbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listbookMouseClicked(evt);
            }
        });
        listbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listbookKeyPressed(evt);
            }
        });
        scrollbook.setViewportView(listbook);

        jPanel2.add(scrollbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 280, 38));

        bprint.setText("Print Summary");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });
        jPanel2.add(bprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 130, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Total Sold Qty:");

        ltotsold.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ltotsold.setForeground(new java.awt.Color(0, 0, 255));
        ltotsold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotsold.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Total Sold Amount:");

        ltotsoldamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ltotsoldamount.setForeground(new java.awt.Color(0, 0, 255));
        ltotsoldamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotsoldamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Total Return Qty:");

        ltotreturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ltotreturn.setForeground(new java.awt.Color(255, 51, 51));
        ltotreturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotreturn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total Return Amount:");

        ltotretamount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ltotretamount.setForeground(new java.awt.Color(255, 51, 51));
        ltotretamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotretamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Sold/Return %:");

        lpercentage.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lpercentage.setForeground(new java.awt.Color(255, 51, 51));
        lpercentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpercentage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38)
                        .addComponent(ltotsold, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ltotreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltotretamount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltotsoldamount, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltotsoldamount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltotsold, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltotreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltotretamount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-558)/2, (screenSize.height-418)/2, 558, 418);
    }// </editor-fold>//GEN-END:initComponents

    private void tbookKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbookKeyReleased
        if(!tbook.getText().trim().equals("")){
            multiuse = new Multiuse();
            multiuse.BookSearch(listbook, scrollbook, tbook.getText());
        
            if(evt.getKeyCode() == KeyEvent.VK_DOWN){
                listbook.grabFocus();
            
            }
        }
        
        
    }//GEN-LAST:event_tbookKeyReleased

    private void listbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listbookMouseClicked
        tbook.setText(""+listbook.getSelectedValue()); 
        scrollbook.setSize(scrollbook.getWidth(), 0);
        tbook.setBackground(Color.white);
        listbook.setVisible(false);  
        scrollbook.setVisible(false);
        this.bookid = multiuse.getBookId(tbook.getText());
        this.booktitle = multiuse.getBookTitle(tbook.getText());
        
    }//GEN-LAST:event_listbookMouseClicked

    private void listbookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listbookKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tbook.setText(""+listbook.getSelectedValue()); 
            scrollbook.setSize(scrollbook.getWidth(), 0);
            tbook.setBackground(Color.white);
            listbook.setVisible(false);  
            scrollbook.setVisible(false);
            this.bookid = multiuse.getBookId(tbook.getText());
            this.booktitle = multiuse.getBookTitle(tbook.getText());
            
        }
        
    }//GEN-LAST:event_listbookKeyPressed

    private void bgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgenerateActionPerformed
//        String inputval = JOptionPane.showInputDialog(null, "Passcode?", "Code!", 1);
//        
//        if(inputval.equals("gihan")){ 
//            System.out.println("Okkkkkkkkkkkkk");
//        }
        
        try {
            if(!dtfrom.getDate().equals("") && !dtto.getDate().equals("") && bookid != 0){
                repbooksum = new Repbooksummary();
                
                soldqty = repbooksum.getTotalSoldQty(getFromDate(), getToDate(), bookid);
                soldamount = repbooksum.getTotalSoldAmount(getFromDate(), getToDate(), bookid);
                returnqty = repbooksum.getTotalReturnQty(getFromDate(), getToDate(), bookid);
                returnamount = repbooksum.getTotalReturnAmount(getFromDate(), getToDate(), bookid);
                
                if(soldqty != 0){
                    percentage = ((double)returnqty / (double)soldqty) * 100;
                }else{
                    percentage = 0.0;
                }
                
                DecimalFormat decimal = new DecimalFormat("#.##");
                
                ltotsold.setText(""+soldqty); 
                ltotsoldamount.setText(""+soldamount); 
                ltotreturn.setText(""+returnqty); 
                ltotretamount.setText(""+returnamount); 
                lpercentage.setText(""+Double.valueOf(decimal.format(percentage)));  
                
            }else{
                JOptionPane.showMessageDialog(null, "Select 2 Dates, Book", "Warning!", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select 2 Dates " + e, "Warning!", 2); 
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_bgenerateActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(this); 
        
            if(pj.printDialog()){
                try {
                    System.out.println("Starting........");
                    pj.print();
                    System.out.println("Done!......");
                } catch (Exception e) {
                    System.out.println("Error: Print Error: " + e);
                }
            }
        
        
        
    }//GEN-LAST:event_bprintActionPerformed
    
    String getFromDate(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String fromdate = df.format(dtfrom.getDate());
        
        return fromdate;
    }
    
    String getToDate(){
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String todate = df.format(dtto.getDate());
        
        return todate;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportbooksingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportbooksingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportbooksingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportbooksingle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reportbooksingle().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bgenerate;
    private javax.swing.JButton bprint;
    private com.toedter.calendar.JDateChooser dtfrom;
    private com.toedter.calendar.JDateChooser dtto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JList listbook;
    private javax.swing.JLabel lpercentage;
    private javax.swing.JLabel ltotretamount;
    private javax.swing.JLabel ltotreturn;
    private javax.swing.JLabel ltotsold;
    private javax.swing.JLabel ltotsoldamount;
    private javax.swing.JScrollPane scrollbook;
    private javax.swing.JTextField tbook;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics g, PageFormat pf, int pageIndex) throws PrinterException {
        if(pageIndex > 0){
            return NO_SUCH_PAGE;
        }
        
        DecimalFormat decimal = new DecimalFormat("#.##");
        
        Graphics2D gr2d = (Graphics2D)g;
        gr2d.translate(pf.getImageableX(), pf.getImageableY());
        
        Font fonth = new Font("arial", Font.BOLD, 12);
        Font fontn = new Font("arial", Font.PLAIN, 10);
        Font fontd = new Font("arial", Font.PLAIN, 8);
        
        g.setFont(fonth); 
        g.drawString("Sathara Prakashakayo", 100, 30); 
        g.setFont(fontn); 
        g.drawString("Book Summary Report", 110, 50);
        
        g.drawLine(20, 60, 300, 60);
        
        g.setFont(fontd);
        g.drawString("Book Title: ", 50, 70);
        g.drawString("" + booktitle + " (" + bookid + ")", 180, 70);
        g.drawString("From: ", 50, 90);
        g.drawString("" + getFromDate(), 180, 90);
        g.drawString("To: ", 50, 110);
        g.drawString("" + getToDate(), 180, 110);
        
        g.drawLine(20, 120, 300, 120);
        
        g.drawString("Total Sold Qty: ", 50, 130);
        g.drawString("" + soldqty, 180, 130);
        g.drawString("Total Return Qty: ", 50, 150);
        g.drawString("" + returnqty, 180, 150);
        g.drawString("Total Sold Amount: ", 50, 170);
        g.drawString("" + soldamount, 180, 170);
        g.drawString("Total Return Amount: ", 50, 190);
        g.drawString("" + returnamount, 180, 190);
        g.drawString("Sold/Return Percentage: ", 50, 190);
        g.drawString("" + Double.valueOf(decimal.format(percentage)), 180, 190);
        
        
        return PAGE_EXISTS;
        
    }
}
