/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import model.Reportsummary;

/**
 *
 * @author Gihan
 */
public class Reportdatesum extends javax.swing.JFrame implements Printable{
    Reportsummary repsummary;
    String repdate;
    int totalinvoices;
    int totalsoldqty;
    int totalreturnqty;
    int cashinvoices;
    int chequeinvoices;
    int bothinvoices;
    int userid;
    double totalamount;
    double cashamount;
    double chequeamount;
    double chequeamount2;
    double totchequeamount;
    double returnamount;
    
    
    /**
     * Creates new form Reportdatesum
     */
    public Reportdatesum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtreport = new com.toedter.calendar.JDateChooser();
        bview = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tuserid = new javax.swing.JTextField();
        pnlreport = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ldate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ltotalinvoices = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ltotalsoldqty = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ltotalretqty = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lcashinvoices = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lchequeinvoices = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbothpayinvoices = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ltotalamount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lcashamount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lchequeamount = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lreturnamount = new javax.swing.JLabel();
        bprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Report - Date Summary");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Date:");

        bview.setText("View Report");
        bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bviewActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("User ID:");

        tuserid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dtreport, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bview, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tuserid, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtreport, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bview, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tuserid, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlreport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Summary Report for:");

        ldate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ldate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ldate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total Invoices:");

        ltotalinvoices.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ltotalinvoices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotalinvoices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Total Sold Qty:");

        ltotalsoldqty.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ltotalsoldqty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotalsoldqty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Total Return Qty:");

        ltotalretqty.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ltotalretqty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotalretqty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cash Invoices:");

        lcashinvoices.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lcashinvoices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcashinvoices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Cheque Invoices:");

        lchequeinvoices.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lchequeinvoices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lchequeinvoices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Both Pay Invoices:");

        lbothpayinvoices.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbothpayinvoices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbothpayinvoices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total Amount:");

        ltotalamount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ltotalamount.setForeground(new java.awt.Color(51, 0, 255));
        ltotalamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltotalamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cash Amount:");

        lcashamount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lcashamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcashamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Cheque Amount:");

        lchequeamount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lchequeamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lchequeamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Return Amount:");

        lreturnamount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lreturnamount.setForeground(new java.awt.Color(255, 0, 51));
        lreturnamount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lreturnamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bprint.setText("Print Report");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlreportLayout = new javax.swing.GroupLayout(pnlreport);
        pnlreport.setLayout(pnlreportLayout);
        pnlreportLayout.setHorizontalGroup(
            pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlreportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlreportLayout.createSequentialGroup()
                        .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(52, 52, 52)
                        .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lchequeamount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(lcashamount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ltotalamount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbothpayinvoices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lchequeinvoices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lcashinvoices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ltotalretqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lreturnamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlreportLayout.createSequentialGroup()
                        .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ltotalsoldqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ltotalinvoices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ldate, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlreportLayout.setVerticalGroup(
            pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlreportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ldate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bprint, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ltotalinvoices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltotalsoldqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltotalretqty, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcashinvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lchequeinvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbothpayinvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcashamount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lchequeamount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lreturnamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlreport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlreport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-484)/2, (screenSize.height-684)/2, 484, 684);
    }// </editor-fold>//GEN-END:initComponents

    private void bviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bviewActionPerformed
        repsummary = new Reportsummary();
        repdate = getReportDate();
        
        if(!tuserid.getText().trim().equals("") && !dtreport.getDate().equals("")){
            userid = Integer.parseInt(tuserid.getText());
            
            totalinvoices = repsummary.getTotalInvoices(repdate, userid);
            totalsoldqty = repsummary.getTotalSoldQty(repdate, userid);
            totalreturnqty = repsummary.getTotalReturnQty(repdate, userid);
            cashinvoices = repsummary.getTotalInvoices(repdate, "cash", userid);
            chequeinvoices = repsummary.getTotalInvoices(repdate, "cheque", userid);
            bothinvoices = repsummary.getTotalInvoices(repdate, "both", userid);
            totalamount = repsummary.getTotalAmount(repdate, userid);
            chequeamount = repsummary.getChequeAmount(repdate, userid);
            chequeamount2 = repsummary.getChequeAmount2(repdate, userid);
            totchequeamount = chequeamount + chequeamount2;
            cashamount = totalamount - totchequeamount;
            returnamount = repsummary.getReturnAmount(repdate, userid);
        
            ldate.setText(repdate); 
            ltotalinvoices.setText(""+totalinvoices);
            ltotalsoldqty.setText(""+totalsoldqty);
            ltotalretqty.setText(""+totalreturnqty);
            lcashinvoices.setText(""+cashinvoices);
            lchequeinvoices.setText(""+chequeinvoices);
            lbothpayinvoices.setText(""+bothinvoices);
            ltotalamount.setText(""+totalamount);
            lchequeamount.setText(""+totchequeamount);
            lcashamount.setText(""+cashamount);
            lreturnamount.setText(""+returnamount);
        }else{
            JOptionPane.showMessageDialog(null, "Type User Id, Select the Date!", "Warning!", 2); 
        }
        
        
        
    }

    @Override
    public void paintComponents(Graphics g) {
        
        
    }//GEN-LAST:event_bviewActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(this); 
        
            if(pj.printDialog()){
                try {
                    System.out.println("Starting........");
                    pj.print();
                    System.out.println("Done!......");
                } catch (Exception e) {
                    System.out.println("Error: Print Error: " + e);
                }
            }
        
        
        
    }//GEN-LAST:event_bprintActionPerformed

    String getReportDate(){
        String repdate = "";
        try {
            if(!dtreport.getDate().equals("")){
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                repdate = df.format(dtreport.getDate());
        
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
        
        return repdate;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportdatesum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportdatesum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportdatesum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportdatesum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reportdatesum().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bprint;
    private javax.swing.JButton bview;
    private com.toedter.calendar.JDateChooser dtreport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbothpayinvoices;
    private javax.swing.JLabel lcashamount;
    private javax.swing.JLabel lcashinvoices;
    private javax.swing.JLabel lchequeamount;
    private javax.swing.JLabel lchequeinvoices;
    private javax.swing.JLabel ldate;
    private javax.swing.JLabel lreturnamount;
    private javax.swing.JLabel ltotalamount;
    private javax.swing.JLabel ltotalinvoices;
    private javax.swing.JLabel ltotalretqty;
    private javax.swing.JLabel ltotalsoldqty;
    private javax.swing.JPanel pnlreport;
    private javax.swing.JTextField tuserid;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics g, PageFormat pf, int pageIndex) throws PrinterException {
        if(pageIndex > 0){
            return NO_SUCH_PAGE;
        }
        
        
        Graphics2D gr2d = (Graphics2D)g;
        gr2d.translate(pf.getImageableX(), pf.getImageableY());
        
        Font fonth = new Font("arial", Font.BOLD, 12);
        Font fontn = new Font("arial", Font.PLAIN, 10);
        Font fontd = new Font("arial", Font.PLAIN, 8);
        
        g.setFont(fonth); 
        g.drawString("Sathara Prakashakayo", 100, 30); 
        g.setFont(fontn); 
        g.drawString("Date Summary Report", 110, 50);
        
        g.drawLine(20, 60, 300, 60);
        
        g.setFont(fontd); 
        g.drawString("Date: ", 50, 70);
        g.drawString("" + repdate, 180, 70);
        g.drawString("Total Invoices: ", 50, 90);
        g.drawString("" + totalinvoices, 180, 90);
        g.drawString("Total Sold Qty: ", 50, 110);
        g.drawString("" + totalsoldqty, 180, 110);
        g.drawString("Total Return Qty: ", 50, 130);
        g.drawString("" + totalreturnqty, 180, 130);
        g.drawString("Cash Invoices: ", 50, 150);
        g.drawString("" + cashinvoices, 180, 150);
        g.drawString("Cheque Invoices: ", 50, 170);
        g.drawString("" + chequeinvoices, 180, 170);
        g.drawString("Both Pay Invoices: ", 50, 190);
        g.drawString("" + bothinvoices, 180, 190);
        g.drawString("Total Amount: ", 50, 210);
        g.drawString("" + totalamount, 180, 210);
        g.drawString("Cash Amount: ", 50, 230);
        g.drawString("" + cashamount, 180, 230);
        g.drawString("Cheque Amount: ", 50, 250);
        g.drawString("" + chequeamount, 180, 250);
        g.drawString("Return Amount: ", 50, 270);
        g.drawString("" + returnamount, 180, 270);
        
        g.drawLine(20, 280, 300, 280); 
        
        return PAGE_EXISTS;
    }

}
