/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Bookprice;
import model.Bookstock;

/**
 *
 * @author Gihan
 */
public class StockUI extends javax.swing.JPanel {
    Book book;
    Bookprice bookprice;
    Bookstock bookstock;
    
    int bookid;
    String booktitle;
    int bookqty;
    /**
     * Creates new form StockUI
     */
    public StockUI() {
        initComponents();
        book = new Book();
        loadTable(book.getBooksToTable3()); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblbooks = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bset = new javax.swing.JButton();
        lbooktitle = new javax.swing.JLabel();
        lbid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lcurrstock = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tnewstock = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tsearch = new javax.swing.JTextField();
        bget = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblbooks.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code", "Book Title", "Type", "Stock Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblbooks.setRowHeight(22);
        tblbooks.setSelectionBackground(new java.awt.Color(51, 51, 255));
        tblbooks.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tblbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbooks);
        tblbooks.getColumnModel().getColumn(0).setMinWidth(50);
        tblbooks.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblbooks.getColumnModel().getColumn(0).setMaxWidth(50);
        tblbooks.getColumnModel().getColumn(1).setMinWidth(50);
        tblbooks.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblbooks.getColumnModel().getColumn(1).setMaxWidth(50);
        tblbooks.getColumnModel().getColumn(3).setMinWidth(100);
        tblbooks.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblbooks.getColumnModel().getColumn(3).setMaxWidth(100);
        tblbooks.getColumnModel().getColumn(4).setMinWidth(60);
        tblbooks.getColumnModel().getColumn(4).setPreferredWidth(60);
        tblbooks.getColumnModel().getColumn(4).setMaxWidth(60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Book Title:");

        bset.setText("Set as Current Qty");
        bset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsetActionPerformed(evt);
            }
        });

        lbooktitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbooktitle.setForeground(new java.awt.Color(51, 102, 255));
        lbooktitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbooktitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbid.setForeground(new java.awt.Color(51, 102, 255));
        lbid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Current Stock:");

        lcurrstock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lcurrstock.setForeground(new java.awt.Color(255, 51, 51));
        lcurrstock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcurrstock.setText("000");
        lcurrstock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("New Stock:");

        tnewstock.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tnewstock.setForeground(new java.awt.Color(255, 51, 51));
        tnewstock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tnewstockKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lcurrstock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tnewstock, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lbid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lcurrstock, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tnewstock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Search Title:");

        tsearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tsearch.setForeground(new java.awt.Color(255, 51, 51));

        bget.setText("Get Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)
                        .addComponent(tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bget, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(bget, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbooksMouseClicked
        bookid = Integer.parseInt(tblbooks.getValueAt(tblbooks.getSelectedRow(), 0).toString()); 
        booktitle = tblbooks.getValueAt(tblbooks.getSelectedRow(), 2).toString();
        bookqty = Integer.parseInt(tblbooks.getValueAt(tblbooks.getSelectedRow(), 4).toString());
        lbooktitle.setText(booktitle); 
        lbid.setText(""+bookid);
        lcurrstock.setText(""+bookqty);
        
        
    }//GEN-LAST:event_tblbooksMouseClicked

    private void bsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsetActionPerformed
        if(tblbooks.getSelectedRow() != -1){
            if(!tnewstock.getText().trim().equals("")){
                bookstock = new Bookstock();
                bookstock.setBookid(bookid); 
                bookstock.setQty(Integer.parseInt(tnewstock.getText()));   
                    if(JOptionPane.showConfirmDialog(null, "Sure to Update Stock Qty?", "Question", 0) == 0){
                        if(bookstock.updateBookQty()){
                            JOptionPane.showMessageDialog(null, "Done! Qty Updated Successfully!", "Done!", 1);
                            loadTable(book.getBooksToTable3());
                            tnewstock.setText(""); 
                        }else{
                            JOptionPane.showMessageDialog(null, "Error! While Updating Book Qty!", "Warning!", 2);
                        }
                    }
            }else{
                JOptionPane.showMessageDialog(null, "Type the New Qty of Selected Book!", "Warning!", 2);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select the Book from Table!", "Warning!", 2);
        }
    }//GEN-LAST:event_bsetActionPerformed

    private void tnewstockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnewstockKeyReleased
        if(!tnewstock.getText().isEmpty()){
            for(int x=0; x < tnewstock.getText().length(); x++){
                char c = tnewstock.getText().charAt(x);
                    if(!Character.isDigit(c)){
                        String text = tnewstock.getText().substring(0, x);
                        tnewstock.setText(null);
                        tnewstock.setText(text);
                        tnewstock.setText(""); 
                    }
            }
        }else{
            tnewstock.setText(""); 
        }
        
    }//GEN-LAST:event_tnewstockKeyReleased
    
    void loadTable(ResultSet rs){
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblbooks.getModel();
        
        try {
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getInt("bookid"));
                vec.add(rs.getString("code"));
                vec.add(rs.getString("title"));
                vec.add(rs.getString("type"));
                vec.add(rs.getInt("qty"));
                dt.addRow(vec); 
            }
            
        } catch (SQLException ex) {
            System.out.println("Error from table interface: " + ex);;
        }
        
    }
    
    void clearTable(){
        DefaultTableModel dt = (DefaultTableModel) tblbooks.getModel();
        int rows = tblbooks.getRowCount();
            for(int x=0; x < rows; x++){
                dt.removeRow(0); 
            }
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bget;
    private javax.swing.JButton bset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbid;
    private javax.swing.JLabel lbooktitle;
    private javax.swing.JLabel lcurrstock;
    private javax.swing.JTable tblbooks;
    private javax.swing.JTextField tnewstock;
    private javax.swing.JTextField tsearch;
    // End of variables declaration//GEN-END:variables
}
