/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import control.Usercontrol;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author Gihan
 */
public class UsermanageUI extends javax.swing.JFrame {
    Usercontrol usercontrol;
    User user;
    int selectid;
    
    /**
     * Creates new form UsermanageUI
     */
    public UsermanageUI() {
        initComponents();
        initialProcesses();
        user = new User();
        loadTable(user.getAllUserDetails()); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcontact = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        pnl2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pwpass1 = new javax.swing.JPasswordField();
        pwpass2 = new javax.swing.JPasswordField();
        badd = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        bdeactivate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusers = new javax.swing.JTable();
        bsetadmin = new javax.swing.JButton();
        bsetuser = new javax.swing.JButton();
        benabled = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Manage Window");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Personal Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Name:");

        jLabel2.setText("Contact No:");

        tcontact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tcontact.setForeground(new java.awt.Color(51, 102, 255));

        tname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tname.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Login Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        tusername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tusername.setForeground(new java.awt.Color(51, 102, 255));

        jLabel5.setText("Confirm Password:");

        pwpass1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwpass1.setForeground(new java.awt.Color(51, 102, 255));

        pwpass2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwpass2.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(54, 54, 54))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(56, 56, 56)))
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwpass1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwpass2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22))
        );

        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bupdate.setText("Save Changes");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        bdeactivate.setText("Deactivate");
        bdeactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeactivateActionPerformed(evt);
            }
        });

        tblusers.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "U.ID", "Name", "Contact", "Username", "Type", "Isactive"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblusers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblusers.setRowHeight(22);
        tblusers.setSelectionBackground(new java.awt.Color(0, 51, 255));
        tblusers.setSelectionForeground(new java.awt.Color(255, 255, 204));
        tblusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblusersMouseClicked(evt);
            }
        });
        tblusers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblusersKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblusers);
        tblusers.getColumnModel().getColumn(0).setMinWidth(50);
        tblusers.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblusers.getColumnModel().getColumn(0).setMaxWidth(50);
        tblusers.getColumnModel().getColumn(2).setMinWidth(100);
        tblusers.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblusers.getColumnModel().getColumn(2).setMaxWidth(100);
        tblusers.getColumnModel().getColumn(3).setMinWidth(80);
        tblusers.getColumnModel().getColumn(3).setPreferredWidth(80);
        tblusers.getColumnModel().getColumn(3).setMaxWidth(80);
        tblusers.getColumnModel().getColumn(4).setMinWidth(50);
        tblusers.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblusers.getColumnModel().getColumn(4).setMaxWidth(50);
        tblusers.getColumnModel().getColumn(5).setMinWidth(60);
        tblusers.getColumnModel().getColumn(5).setPreferredWidth(60);
        tblusers.getColumnModel().getColumn(5).setMaxWidth(60);

        bsetadmin.setText("Set-Admin");
        bsetadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsetadminActionPerformed(evt);
            }
        });

        bsetuser.setText("Set-User");
        bsetuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsetuserActionPerformed(evt);
            }
        });

        benabled.setText("Enable Add");
        benabled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benabledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bdeactivate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bsetadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bsetuser, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(benabled, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badd)
                    .addComponent(bupdate)
                    .addComponent(bdeactivate)
                    .addComponent(bsetadmin)
                    .addComponent(bsetuser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(benabled)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-928)/2, (screenSize.height-461)/2, 928, 461);
    }// </editor-fold>//GEN-END:initComponents

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        if(fillAll()){
            if(passwordMatch()){
                user = new User();
                usercontrol = new Usercontrol();
                user.setUsername(tusername.getText()); 
                user.setPassword(pwpass1.getText());
                user.setName(tname.getText());
                user.setContact(tcontact.getText());
                user.setUtype(2);
                user.setCompanyid(1); 
                    if(user.addNewUser()){
                        JOptionPane.showMessageDialog(null, "Done! Successfully Added New User!", "Done!", 1);
                        clearAll();
                        loadTable(user.getAllUserDetails()); 
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Error! fromcontrol, Try again", "Error!", 0);
                    }
                
            }else{
                JOptionPane.showMessageDialog(null, "Both Passwords Must be Same!", "Warning!", 2); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Fill all Details!", "Warning!", 2); 
        }
    }//GEN-LAST:event_baddActionPerformed

    private void tblusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblusersMouseClicked
        pnl2.setEnabled(false); 
        tusername.setEnabled(false); 
        pwpass1.setEnabled(false); 
        pwpass2.setEnabled(false); 
        badd.setEnabled(false);
        bupdate.setEnabled(true); 
        bdeactivate.setEnabled(true);
        bsetadmin.setEnabled(true);
        bsetuser.setEnabled(true);
        selectid = Integer.parseInt(tblusers.getValueAt(tblusers.getSelectedRow(), 0).toString()); 
        tname.setText(""+tblusers.getValueAt(tblusers.getSelectedRow(), 1));
        tcontact.setText(""+tblusers.getValueAt(tblusers.getSelectedRow(), 2));
    }//GEN-LAST:event_tblusersMouseClicked

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        try {
            if(tblusers.getSelectedRow() != -1){
                if(!tname.getText().trim().equals("") && !tname.getText().trim().equals("")){
                    user = new User();
                    if(user.updateUser(selectid, tname.getText(), tcontact.getText())){
                        JOptionPane.showMessageDialog(null, "Done! Update Success!", "Done!", 2);
                        clearAll();
                        loadTable(user.getAllUserDetails());
                    }else{
                        JOptionPane.showMessageDialog(null, "Error! While Updating, Try Again!", "Error!", 1);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Fill both Fields!", "Warning!", 2);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2); 
        }
        
    }//GEN-LAST:event_bupdateActionPerformed

    private void bdeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeactivateActionPerformed
        try {
            if(tblusers.getSelectedRow() != -1){
                if(JOptionPane.showConfirmDialog(null, "Do You Really Want to Deactivate the Selected User?", "Question", 0) == 0){
                    user = new User();
                        if(user.deactivateUser(Integer.parseInt(tblusers.getValueAt(tblusers.getSelectedRow(), 0).toString()))){
                            JOptionPane.showMessageDialog(null, "Done! Deactivated the User!", "Done!", 2);
                            loadTable(user.getAllUserDetails());
                        }else{
                            JOptionPane.showMessageDialog(null, "Error! While Deactivating, Try Again!", "Error!", 1);
                        }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2);
        }
    }//GEN-LAST:event_bdeactivateActionPerformed

    private void bsetadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsetadminActionPerformed
        try {
            if(tblusers.getSelectedRow() != -1){
                if(JOptionPane.showConfirmDialog(null, "Do You Really Want to Set the Selected User as Admin?", "Question", 0) == 0){
                    user = new User();
                        if(user.setUserAsAdmin(Integer.parseInt(tblusers.getValueAt(tblusers.getSelectedRow(), 0).toString()))){ 
                            JOptionPane.showMessageDialog(null, "Done! Set as Administrator!", "Done!", 2);
                            loadTable(user.getAllUserDetails());
                        }else{
                            JOptionPane.showMessageDialog(null, "Error! While Setting, Try Again!", "Error!", 1);
                        }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2);
        }
    }//GEN-LAST:event_bsetadminActionPerformed

    private void bsetuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsetuserActionPerformed
        try {
            if(tblusers.getSelectedRow() != -1){
                if(JOptionPane.showConfirmDialog(null, "Do You Really Want to Set the Selected Admin as User?", "Question", 0) == 0){
                    user = new User();
                        if(user.setAdminAsUser(Integer.parseInt(tblusers.getValueAt(tblusers.getSelectedRow(), 0).toString()))){ 
                            JOptionPane.showMessageDialog(null, "Done! Set Admin as User!", "Done!", 2);
                            loadTable(user.getAllUserDetails());
                        }else{
                            JOptionPane.showMessageDialog(null, "Error! While Setting!, Try Again!", "Error!", 1);
                        }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select User from Table!", "Warning!", 2);
        }
    }//GEN-LAST:event_bsetuserActionPerformed

    private void tblusersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblusersKeyReleased
        pnl2.setEnabled(false); 
        tusername.setEnabled(false); 
        pwpass1.setEnabled(false); 
        pwpass2.setEnabled(false); 
        badd.setEnabled(false); 
        selectid = Integer.parseInt(tblusers.getValueAt(tblusers.getSelectedRow(), 0).toString()); 
        tname.setText(""+tblusers.getValueAt(tblusers.getSelectedRow(), 1));
        tcontact.setText(""+tblusers.getValueAt(tblusers.getSelectedRow(), 2));
    }//GEN-LAST:event_tblusersKeyReleased

    private void benabledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benabledActionPerformed
        pnl2.setEnabled(true); 
        tusername.setEnabled(true); 
        pwpass1.setEnabled(true); 
        pwpass2.setEnabled(true); 
        badd.setEnabled(true);
        tname.setText("");
        tcontact.setText("");
        initialProcesses();
    }//GEN-LAST:event_benabledActionPerformed
    
    boolean fillAll(){
        boolean val = false;
        
        if(tname.getText().trim().equals("") || tcontact.getText().trim().equals("") || tusername.getText().trim().equals("") || pwpass1.getText().trim().equals("") || pwpass2.getText().trim().equals("")){ 
            val = false;
        }else{
            val = true;
        }
        
        
        return val;
    }
    
    boolean passwordMatch(){
        boolean val = false;
        
        if(pwpass1.getText().trim().equals(pwpass2.getText().trim())){
            val = true;
        }else{
            val = false;
        }
        
        return val;
    }
    
    void loadTable(ResultSet rs){
        clearTable();
        DefaultTableModel dt = (DefaultTableModel) tblusers.getModel();
        
        try {
            while(rs.next()){
                Vector vec = new Vector();
                vec.add(rs.getInt("userid"));
                vec.add(rs.getString("name"));
                vec.add(rs.getString("contactno"));
                vec.add(rs.getString("username"));
                vec.add(rs.getString("usertypeutypeid"));
                vec.add(rs.getInt("isactive"));
                dt.addRow(vec); 
            }
            
        } catch (SQLException ex) {
            System.out.println("Error from table interface: " + ex);;
        }
        
    }
    
    void clearTable(){
        DefaultTableModel dt = (DefaultTableModel) tblusers.getModel();
        int rows = tblusers.getRowCount();
            for(int x=0; x < rows; x++){
                dt.removeRow(0); 
            }
        
    }
    
    void clearAll(){
        tname.setText(""); 
        tcontact.setText(""); 
        tusername.setText(""); 
        pwpass1.setText(""); 
        pwpass2.setText(""); 
        
    }
    
    void initialProcesses(){
        bupdate.setEnabled(false); 
        bdeactivate.setEnabled(false);
        bsetadmin.setEnabled(false);
        bsetuser.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsermanageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsermanageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsermanageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsermanageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UsermanageUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton bdeactivate;
    private javax.swing.JButton benabled;
    private javax.swing.JButton bsetadmin;
    private javax.swing.JButton bsetuser;
    private javax.swing.JButton bupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPasswordField pwpass1;
    private javax.swing.JPasswordField pwpass2;
    private javax.swing.JTable tblusers;
    private javax.swing.JTextField tcontact;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
}
